# Generated by Django 4.0 on 2023-05-24 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='unique_number',
            field=models.CharField(db_index=True, max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Unique number must be in the format of 4 digits followed by one uppercase letter.', regex='^[1-9]\\d{3}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
